"""Preprocessing and cleanup of raw diff ops before display."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_clean.ipynb.

# %% auto #0
__all__ = ['clean_newlines', 'extract_newlines_to_blocks', 'add_accepted_flags']

# %% ../nbs/02_clean.ipynb #bd8a9e58
import re
from typing import List, Dict, Any

# %% ../nbs/02_clean.ipynb #0b042865
def clean_newlines(ops: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Auto-accept changes that are ONLY whitespace/newlines.
    
    Runs before grouping to ensure formatting changes don't noise up the diffs.
    After cleaning, merges consecutive ops of the same simple type."""
    is_whitespace = lambda t: t is not None and bool(re.match(r'^\s+$', t))
    cleaned = []

    for seg in ops:
        op_type = seg.get("type")
        text = seg.get("text", "")

        if op_type == 'add':
            if is_whitespace(text):
                cleaned.append({**seg, 'type': 'equal'})
            else:
                cleaned.append(seg)

        elif op_type == 'remove':
            if is_whitespace(text):
                continue  # drop whitespace-only removals
            else:
                cleaned.append(seg)

        elif op_type == 'replace':
            old_t = seg.get('old_text', '')
            new_t = seg.get('new_text', '')

            if is_whitespace(old_t) and is_whitespace(new_t):
                cleaned.append({'type': 'equal', 'text': new_t})
            elif is_whitespace(old_t) and not new_t:
                continue
            elif not old_t and is_whitespace(new_t):
                cleaned.append({'type': 'equal', 'text': new_t})
            else:
                cleaned.append(seg)
        else:
            cleaned.append(seg)

    # Merge consecutive ops of the same simple type
    if not cleaned:
        return []

    merged = []
    current = cleaned[0].copy()

    for next_seg in cleaned[1:]:
        if (current['type'] == next_seg['type'] and
            current['type'] in ['equal', 'add', 'remove'] and
            'text' in current and 'text' in next_seg):
            current['text'] += next_seg['text']
        else:
            merged.append(current)
            current = next_seg.copy()

    merged.append(current)
    return merged

# %% ../nbs/02_clean.ipynb #6429e774
def extract_newlines_to_blocks(ops: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Extract all newlines into their own separate equal blocks.
    
    Rules:
    - Newlines in equal/add blocks -> separate equal blocks
    - Newlines in remove blocks -> dropped (not shown)
    - Newlines in replace blocks -> separate equal blocks (when symmetric)"""
    if not ops:
        return []

    result = []

    for op in ops:
        op_type = op["type"]

        if op_type == "replace":
            old_text = op.get("old_text", "")
            new_text = op.get("new_text", "")
            old_parts = old_text.split("\n")
            new_parts = new_text.split("\n")

            if len(old_parts) == len(new_parts):
                for i, (old_part, new_part) in enumerate(zip(old_parts, new_parts)):
                    if old_part or new_part:
                        result.append({"type": "replace", "old_text": old_part, "new_text": new_part})
                    if i < len(old_parts) - 1:
                        result.append({"type": "equal", "text": "\n"})
            else:
                # Asymmetric newlines - keep as-is
                result.append(op)

        elif op_type in ("equal", "add"):
            text = op.get("text", "")
            parts = text.split("\n")
            for i, part in enumerate(parts):
                if part:
                    result.append({"type": op_type, "text": part})
                if i < len(parts) - 1:
                    result.append({"type": "equal", "text": "\n"})

        elif op_type == "remove":
            text = op.get("text", "")
            parts = text.split("\n")
            for part in parts:
                if part:
                    result.append({"type": "remove", "text": part})

        else:
            result.append(op)

    return result

# %% ../nbs/02_clean.ipynb #433f0f7c
def add_accepted_flags(ops: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Add `accepted` field to ops based on auto-accept rules.
    
    - equal blocks -> always accepted
    - replace that deletes 1-3 spaces (old=' '/' '/'   ', new='') -> convert to equal
    - add/remove -> not accepted (pending user review)"""
    if not ops:
        return []

    result = []
    for op in ops:
        op_type = op.get("type")

        if op_type == "equal":
            result.append({"type": "equal", "text": op.get("text", ""), "accepted": True})

        elif op_type == "replace":
            old_text = op.get("old_text", "")
            new_text = op.get("new_text", "")
            if len(new_text) == 0 and old_text in (' ', '  ', '   '):
                result.append({"type": "equal", "text": new_text, "accepted": True})
            else:
                result.append({"type": "replace", "old_text": old_text, "new_text": new_text, "accepted": False})

        elif op_type == "add":
            result.append({"type": "add", "text": op.get("text", ""), "accepted": False})

        elif op_type == "remove":
            result.append({"type": "remove", "text": op.get("text", ""), "accepted": False})

        else:
            result.append(op.copy())

    return result
