# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['Segment', 'DocumentState']

# %% ../nbs/00_core.ipynb #a46d0c5d
from dataclasses import dataclass, field, asdict
from copy import deepcopy
from typing import List, Dict, Any, Optional
import uuid

# %% ../nbs/00_core.ipynb #6a922621
@dataclass
class Segment:
    id: str
    text: str
    segment_type: str # "keep", "add", "remove"
    explanation: str = ""
    accepted: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)
    
    @staticmethod
    def from_dict(data: Dict[str, Any]) -> 'Segment':
        return Segment(**data)


# %% ../nbs/00_core.ipynb #020352bb
@dataclass
class DocumentState:
    """Complete document state with history tracking."""
    segments: List[Segment] = field(default_factory=list)
    history: List[List[Segment]] = field(default_factory=list)
    history_index: int = -1

    def add_segments(self, segments_data: List[Dict[str, Any]]) -> None:
        """Initialize or replace segments from a list of dicts."""
        self.segments = [Segment.from_dict(data) for data in segments_data]
        self._push_history()

    def edit_segment(self, segment_id: str, new_text: str) -> bool:
        """Edit a segment's text. Returns True if found."""
        segment_index = self._find_segment_index(segment_id)
        if segment_index is None:
            return False
        self.segments[segment_index].text = new_text
        self._push_history()
        return True

    def accept_segment(self, segment_id: str, action: str) -> bool:
        """
        Accept or reject a segment change.

        Actions:
        - 'keep-remove': keep text that was marked for removal
        - 'accept-remove': actually remove the segment
        - 'keep-add': accept an addition (convert to keep)
        - 'reject-add': reject an addition (delete segment)
        - 'remove': for a replace pair, keep the old text
        - 'add': for a replace pair, keep the new text
        """
        segment_index = self._find_segment_index(segment_id)
        if segment_index is None:
            return False

        if action in ("reject-add", "accept-remove"):
            self.segments.pop(segment_index)

        elif action in ("keep-remove", "keep-add"):
            self.segments[segment_index].segment_type = "keep"

        elif action in ("remove", "add"):
            if segment_index + 1 >= len(self.segments):
                return False
            if not self._is_change_pair(self.segments[segment_index], self.segments[segment_index + 1]):
                return False

            if action == "remove":
                kept_text = self.segments[segment_index].text
            else:
                kept_text = self.segments[segment_index + 1].text

            new_segment = Segment(
                id=str(uuid.uuid4()),
                text=kept_text,
                segment_type='keep',
                explanation='',
                accepted=True
            )
            self.segments[segment_index:segment_index + 2] = [new_segment]
        else:
            return False

        self._push_history()
        return True

    def undo(self) -> bool:
        """Undo last change. Returns True if there was something to undo."""
        if len(self.history) == 1 or self.history_index == 0:
            return False
        else:
            self.history_index -= 1
        self.segments = deepcopy(self.history[self.history_index])
        return True

    def redo(self) -> bool:
        """Redo last undone change. Returns True if there was something to redo."""
        if len(self.history) == 1 or self.history_index == len(self.history) - 1:
            return False
        self.history_index += 1
        self.segments = deepcopy(self.history[self.history_index])
        return True

    def get_working_text(self) -> str:
        """Get the current working text (includes kept and removed text)."""
        working_text = ""
        for segment in self.segments:
            if segment.segment_type in ("keep", "remove"):
                working_text += segment.text
        return working_text

    def get_final_text(self) -> str:
        """Get the final text (only accepted/kept segments)."""
        working_text = ""
        for segment in self.segments:
            if segment.segment_type == "keep":
                working_text += segment.text
        return working_text

    def to_dict(self) -> Dict[str, Any]:
        """Serialize the full state including undo/redo availability."""
        return {
            "segments": [seg.to_dict() for seg in self.segments],
            "can_undo": self.history_index > 0,
            "can_redo": self.history_index < len(self.history) - 1,
            "working_text": self.get_working_text(),
            "final_text": self.get_final_text(),
        }

    def _push_history(self) -> None:
        """Snapshot current segments into history, truncating any future states."""
        self.history = self.history[:self.history_index+1] + [deepcopy(self.segments)]
        self.history_index = len(self.history)-1

    def _find_segment_index(self, segment_id: str) -> Optional[int]:
        """Find a segment's index by id. Returns None if not found."""
        for i, seg in enumerate(self.segments):
            if seg.id == segment_id:
                return i
        return None

    def _is_change_pair(self, seg1: Segment, seg2: Segment) -> bool:
        """Check if two segments form a remove+add (or add+remove) pair."""
        return (seg1.segment_type == "remove" and seg2.segment_type == "add")
