"""Word-level diff computation with whitespace preservation."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_diff.ipynb.

# %% auto #0
__all__ = ['tokenize_preserving_whitespace', 'compute_diff']

# %% ../nbs/01_diff.ipynb #47a10f28
import re
from difflib import SequenceMatcher
from typing import List, Dict, Any

# %% ../nbs/01_diff.ipynb #06f28f1c
def tokenize_preserving_whitespace(text: str) -> List[str]:
    """Split text into tokens (words and whitespace) preserving all characters."""
    tokens = re.split(r'(\s+)', text)
    return [t for t in tokens if t]

# %% ../nbs/01_diff.ipynb #baca1a8f
def compute_diff(original: str, rewritten: str) -> List[Dict[str, Any]]:
    """Compute word-level diff between original and rewritten text.
    
    Returns a list of ops: equal, add, remove, replace.
    This is the raw diff — no cleanup or grouping applied."""
    if not original and not rewritten:
        return [{"type": "equal", "text": ""}]
    if not original:
        return [{"type": "add", "text": rewritten}]
    if not rewritten:
        return [{"type": "remove", "text": original}]

    A = tokenize_preserving_whitespace(original)
    B = tokenize_preserving_whitespace(rewritten)
    # autojunk=False is essential: with the default (True), SequenceMatcher
    # treats any token in >1% of a sequence longer than 200 items as "popular
    # junk" and skips it when matching. In prose that hits the space token and
    # common words (the/to/a/and) — exactly the anchors that keep edits
    # word-sized — so a long document collapses into paragraph-sized
    # replacements. Disabling autojunk keeps changes word-level on any length.
    sm = SequenceMatcher(None, A, B, autojunk=False)
    ops = []

    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == "equal":
            ops.append({"type": "equal", "text": "".join(A[i1:i2])})
        elif tag == "insert":
            ops.append({"type": "add", "text": "".join(B[j1:j2])})
        elif tag == "delete":
            ops.append({"type": "remove", "text": "".join(A[i1:i2])})
        elif tag == "replace":
            ops.append({"type": "replace", "old_text": "".join(A[i1:i2]), "new_text": "".join(B[j1:j2])})

    return ops
