"""LLM-powered text rewriting, semantic grouping, and end-to-end pipeline."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_llm.ipynb.

# %% auto #0
__all__ = ['DEFAULT_MODEL', 'get_llm_rewrite', 'get_semantic_groups', 'llm_semantic_grouping', 'process_diff',
           'request_text_improvement']

# %% ../nbs/04_llm.ipynb #ae6d21ed
import os
import json
import httpx
from typing import List, Dict, Any

from .diff import compute_diff
from .clean import clean_newlines, extract_newlines_to_blocks, add_accepted_flags
from .group import group_replacements, apply_semantic_groups

# %% ../nbs/04_llm.ipynb #b715dd34
DEFAULT_MODEL = "qwen/qwen3.5-flash-02-23"

# %% ../nbs/04_llm.ipynb #09ad5376
async def get_llm_rewrite(
    problem_description: str,
    current_text: str,
    api_key: str,
    model: str = "",
) -> str:
    """Ask an LLM to rewrite `current_text` to achieve `problem_description`.
    
    Returns the rewritten text string."""
    url = "https://openrouter.ai/api/v1/chat/completions"
    model = model or DEFAULT_MODEL

    system_instruction = (
        "You are a professional text editor.\n"
        "Your task: Rewrite the provided text to achieve the user's goal.\n"
        "IMPORTANT:\n"
        "- Return ONLY the rewritten text\n"
        "- Do NOT add explanations, commentary, or markdown formatting"
    )

    user_prompt = f"Goal: {problem_description}\n\nOriginal Text:\n{current_text}\n\nRewritten Text:"

    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_instruction},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": 0.7,
    }

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }

    async with httpx.AsyncClient() as client:
        response = await client.post(url, json=payload, headers=headers, timeout=60.0)
        response.raise_for_status()
        data = response.json()
        return data["choices"][0]["message"]["content"].strip()

# %% ../nbs/04_llm.ipynb #f60760b0
async def get_semantic_groups(
    diff_items: List[Dict[str, Any]],
    api_key: str,
    model: str = "",
) -> List[List[int]]:
    """Ask the LLM which diff items should be grouped together.
    
    Returns a list of groups, where each group is a list of indices to merge."""
    url = "https://openrouter.ai/api/v1/chat/completions"
    model = model or DEFAULT_MODEL

    system_instruction = (
        "You are a text diff analyzer. Group related changes together for better UX.\n\n"
        "GROUPING RULES:\n"
        "1. Group changes that are grammatically or semantically dependent\n"
        "2. Group consecutive changes that form a single logical edit\n"
        "3. Keep independent changes separate\n"
        "4. Never group changes separated by significant equal text (more than a few words)\n"
        '5. Never group changes across newline boundaries (type "equal" with text "\\n")\n\n'
        "Return ONLY a JSON array of groups, where each group is an array of indices to merge.\n"
        'Example: [[0, 1, 2], [4, 5]] means merge items 0,1,2 together and 4,5 together.\n'
        'If no grouping needed, return empty array: []'
    )

    user_prompt = (
        "Analyze this diff and suggest which consecutive items should be grouped together:\n\n"
        f"{json.dumps(diff_items, indent=2)}\n\n"
        "Return only the JSON array of groups (arrays of indices to merge)."
    )

    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_instruction},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": 0.3,
    }

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }

    async with httpx.AsyncClient() as client:
        response = await client.post(url, json=payload, headers=headers, timeout=60.0)
        response.raise_for_status()
        data = response.json()
        content = data["choices"][0]["message"]["content"].strip()

        # Handle markdown code fences in response
        if "```" in content:
            start = content.find("[")
            end = content.rfind("]") + 1
            if start != -1 and end != 0:
                content = content[start:end]

        return json.loads(content)

# %% ../nbs/04_llm.ipynb #4608b20d
async def llm_semantic_grouping(
    ops: List[Dict[str, Any]],
    api_key: str,
    model: str = "",
) -> List[Dict[str, Any]]:
    """Use an LLM to intelligently group semantically related diff ops.
    
    Wraps `get_semantic_groups` + `apply_semantic_groups`.
    Falls back to returning `ops` unchanged if the LLM call fails."""
    if not ops or len(ops) <= 2:
        return ops
    if all(op.get("type") == "equal" for op in ops):
        return ops

    try:
        # Build simplified view for the LLM
        diff_for_llm = []
        for idx, op in enumerate(ops):
            op_type = op.get("type")
            if op_type == "equal":
                diff_for_llm.append({"index": idx, "type": "equal", "text": op.get("text", "")})
            elif op_type == "replace":
                diff_for_llm.append({"index": idx, "type": "replace", "old": op.get("old_text", ""), "new": op.get("new_text", "")})
            elif op_type == "add":
                diff_for_llm.append({"index": idx, "type": "add", "text": op.get("text", "")})
            elif op_type == "remove":
                diff_for_llm.append({"index": idx, "type": "remove", "text": op.get("text", "")})

        groups = await get_semantic_groups(diff_for_llm, api_key, model)
        return apply_semantic_groups(ops, groups)

    except Exception as e:
        print(f"LLM semantic grouping failed: {e}")
        return ops

# %% ../nbs/04_llm.ipynb #7bb74bdf
async def process_diff(
    original: str,
    rewritten: str,
    api_key: str = "",
    model: str = "",
    semantic_grouping: bool = True,
) -> List[Dict[str, Any]]:
    """Run the full diff pipeline: diff -> clean -> group -> extract newlines -> flag -> (optional) LLM grouping.
    
    Set `semantic_grouping=False` to skip the LLM semantic grouping step."""
    # Raw diff
    ops = compute_diff(original, rewritten)

    # Clean whitespace noise
    cleaned = clean_newlines(ops)
    if not cleaned:
        return [{"type": "equal", "text": original, "accepted": True}]

    # If no real changes remain, return early
    if all(op["type"] == "equal" for op in cleaned):
        return add_accepted_flags(cleaned)

    # Group consecutive replacements
    grouped = group_replacements(cleaned)

    # Extract newlines into their own blocks
    newline_extracted = extract_newlines_to_blocks(grouped)

    # Add accepted flags
    flagged = add_accepted_flags(newline_extracted)

    # Optional LLM semantic grouping
    if semantic_grouping and api_key:
        flagged = await llm_semantic_grouping(flagged, api_key, model)

    return flagged

# %% ../nbs/04_llm.ipynb #8dda0d3e
async def request_text_improvement(
    problem_description: str,
    current_text: str,
    api_key: str = "",
    model: str = "",
    semantic_grouping: bool = True,
) -> List[Dict[str, Any]]:
    """End-to-end: LLM rewrite then diff pipeline.
    
    1. Ask LLM to rewrite `current_text` according to `problem_description`
    2. Compute and process the diff between original and rewritten
    
    Returns a list of diff ops ready for display."""
    final_api_key = api_key or os.environ.get("OPENROUTER_API_KEY", "")

    if not final_api_key:
        return [
            {"text": "Error: API Key missing. ", "type": "equal", "accepted": True},
            {"text": "Please provide your OpenRouter API key.", "type": "add", "accepted": False},
        ]

    try:
        rewritten = await get_llm_rewrite(problem_description, current_text, final_api_key, model)
        return await process_diff(current_text, rewritten, final_api_key, model, semantic_grouping)
    except Exception as e:
        print(f"LLM Call Failed: {e}")
        return [
            {"text": "Error processing text: ", "type": "equal", "accepted": True},
            {"text": str(e), "type": "add", "accepted": False},
        ]
